# -*- coding: utf-8 -*-
"""Family Ledger Tool

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E7YorrwnhPvAdB-D1APbWgpX_4Vzyehi
""" 

# THE FAMILY LEDGER — Community Edition
# Built by Aashvi Bansal | Family Financial Health Tool

# ==============================
# MODULE 1 — INPUT HANDLING
# ==============================
# pyrefly: ignore [missing-import]
import matplotlib.pyplot as plt
import numpy as np 
def get_rupees(prompt):
    try:
        val = input(prompt + " (₹): ")
        return float(val) if val.strip() else 0.0
    except ValueError:
      print("Invalid amount. Please enter a number and try again.")
    return get_rupees(prompt)

# ==============================
# MODULE 2 — DATA COLLECTION
# ==============================
def collect_data():
  print("\n=== FAMILY FINANCIAL HEALTH CALCULATOR ===")
  print("Built by Aashvi Bansal | The Family Ledger Project\n")
  income = get_rupees('Total monthly household income')
  print('\nEnter monthly expenses (press Enter to skip any):')
  expenses = {
    'Housing (rent/EMI)' : get_rupees('Housing/rent/EMI'),
    'Food & groceries' : get_rupees('Food & groceries'),
    'Education fees' : get_rupees('Education fees'),
    'Utilities' : get_rupees('Utilities (electricity/gas/water)'),
    'Transport' : get_rupees('Transport'),
    'Mobile & internet' : get_rupees('Mobile & internet'),
    'Medical' : get_rupees('Medical'),
    'Clothing' : get_rupees('Clothing & personal care'),
    'Entertainment' : get_rupees('Entertainment & dining out'),
    'Insurance/LIC' : get_rupees('Insurance / LIC premiums'),
    'Loan EMIs' : get_rupees('Loan EMIs'),
  }
  monthly_savings = get_rupees('Current monthly savings / RD / SIP (optional)')
  return income, expenses, monthly_savings


# ==============================
# MODULE 3 — BUDGET ANALYSIS
# ==============================
def analyse (income,expenses):
  total_exp = sum(expenses.values())
  surplus = income-total_exp
  remaining_pct = (surplus / income * 100) if income else 0
  expense_pct = (total_exp / income * 100) if income else 0

  fixed = (expenses['Housing (rent/EMI)'] +
         expenses['Education fees'] +
         expenses['Insurance/LIC'] +
         expenses['Loan EMIs'])

  variable = (expenses['Food & groceries'] +
                expenses['Utilities'] +
                expenses['Transport'] +
                expenses['Mobile & internet'] +
                expenses['Medical'])

  discretionary = (expenses['Clothing'] +
                expenses['Entertainment'])

  fixed_pct = (fixed / income * 100) if income else 0
  variable_pct = (variable / income * 100) if income else 0
  discretionary_pct = (discretionary / income * 100) if income else 0

  potential_monthly_saving = variable * 0.10
  potential_annual_saving = potential_monthly_saving * 12

  return {
        'income': income,
        'total_exp': total_exp,
        'surplus': surplus,
        'remaining_pct': remaining_pct,
        'expense_pct' : expense_pct,
        'fixed': fixed,
        'variable': variable,
        'discretionary': discretionary,
        'fixed_pct': fixed_pct,
        'variable_pct': variable_pct,
        'discretionary_pct': discretionary_pct,

        'potential_monthly_saving': potential_monthly_saving,
        'potential_annual_saving': potential_annual_saving,
    }

def show_analysis(results):

    print("\n=== BUDGET ANALYSIS ===")

    print(f"\nMonthly income: ₹{results['income']:,.0f}")
    print(f"Monthly expenses: ₹{results['total_exp']:,.0f}")
    print(f"Money remaining: ₹{results['surplus']:,.0f}")

    print(f"\nIncome used for expenses: {results['expense_pct']:.1f}%")
    print(f"Income remaining: {results['remaining_pct']:.1f}%")

    print("\n--- EXPENSE STRUCTURE ---")

    print(f"Fixed expenses: ₹{results['fixed']:,.0f} "
          f"({results['fixed_pct']:.1f}%)")
    print(f"Variable essential expenses: ₹{results['variable']:,.0f} "
          f"({results['variable_pct']:.1f}%)")

    print(f"Discretionary expenses: ₹{results['discretionary']:,.0f} "
          f"({results['discretionary_pct']:.1f}%)")

    print("\n--- POTENTIAL IMPROVEMENT SCENARIO ---")

    print("If variable expenses were reduced by 10%:")

    print(f"Potential amount freed per month: "
          f"₹{results['potential_monthly_saving']:,.0f}")

    print(f"Potential amount freed per year: "
          f"₹{results['potential_annual_saving']:,.0f}")

# ==============================
# MODULE 4 — COMPOUNDING PROJECTOR
# ==============================
def compound(monthly, years=5, annual_rate=0.07):
  r = annual_rate / 12
  n = years * 12
  return monthly * ((1 + r) ** n - 1) / r

def project_savings(monthly_savings, result):
    potential = result['potential_monthly_saving']
    discretionary = result['discretionary']
    discretionary_pct = result['discretionary_pct']

    scenarios = []
         # Scenario 1 — Current savings
    if monthly_savings > 0:
        scenarios.append(
            ('Current savings', monthly_savings)
        )
         # Scenario 2 — Current savings + 10% variable reduction
        moderate = monthly_savings + potential

        scenarios.append(
            ('+ 10% variable reduction', moderate)
        )
        # Scenario 3 — Optimised scenario
        if discretionary_pct > 20:
            discretionary_reduction = discretionary * 0.15
            optimised = (
                monthly_savings
                + potential
                + discretionary_reduction
            )
            scenarios.append(
                ('Optimised scenario', optimised)
            )
    else:
        # No current savings provided
        scenarios.append(
            ('Illustrative: 10% variable reduction', potential)
        )

        # Additional scenario if discretionary spending is above 20%
        if discretionary_pct > 20:
            discretionary_reduction = discretionary * 0.15
            optimised = potential + discretionary_reduction
            scenarios.append(
                ('Illustrative: variable + discretionary reduction',
                 optimised)
            )
    print("\n=== 5-YEAR COMPOUNDING PROJECTION ===")
    print("Assumed annual return: 7%")
    print("Projection period: 5 years")
    if monthly_savings == 0:
        print("Current monthly savings were not provided.")
        print("The projection is illustrative.")
    for label, monthly in scenarios:
        fv = compound(monthly)
        print(
            f"\n{label}:"
            f"\n  ₹{monthly:,.0f}/month"
            f" → ₹{fv:,.0f} after 5 years"
        )
    return scenarios

# ==============================
# MODULE 5 — GOVERNMENT SCHEME ELIGIBILITY
# ==============================

def check_pmjay_senior(age_70_plus):
    if age_70_plus:
        print("\nPM-JAY 70+ — Potentially relevant.")
        print("A household member aged 70+ meets the age criterion.")
        print("Final enrolment requires official verification.")
        return True
    else:
        print("\nPM-JAY 70+ — Does not appear applicable.")
        return False


def check_surya_ghar():
    print("\n=== PM SURYA GHAR: MUFT BIJLI YOJANA ===")

    while True:
        electricity = input(
            "Does the household have a residential electricity connection? (yes/no): "
        ).strip().lower()

        if electricity == "yes":
            break
        elif electricity == "no":
            print("\nPM Surya Ghar — Does not appear applicable.")
            return False
        else:
            print("\nPlease enter only 'yes' or 'no'.")

    while True:
        rooftop = input(
            "Does the household have a suitable rooftop/location for solar installation? (yes/no): "
        ).strip().lower()

        if rooftop == "yes":
            break
        elif rooftop == "no":
            print("\nPM Surya Ghar — Does not appear applicable.")
            return False
        else:
            print("\nPlease enter only 'yes' or 'no'.")

    while True:
        subsidy = input(
            "Has the household already received PM Surya Ghar rooftop-solar subsidy? (yes/no): "
        ).strip().lower()

        if subsidy == "yes":
            print("\nPM Surya Ghar — Already utilised.")
            return False
        elif subsidy == "no":
            break
        else:
            print("\nPlease enter only 'yes' or 'no'.")

    print("\nPM Surya Ghar — Potentially relevant for further verification.")
    return True


def check_pmay_u20(income):
    print("\n=== PMAY-U 2.0 — HOUSING SCREENING ===")

    annual_income = income * 12

    if annual_income > 900000:
        print("\nPMAY-U 2.0 — Does not appear applicable based on income.")
        return False

    while True:
        urban = input("Does the household live in an urban area? (yes/no): ").strip().lower()

        if urban == "yes":
            break
        elif urban == "no":
            print("\nPMAY-U 2.0 is an urban housing scheme.")
            return False
        else:
            print("\nPlease enter only 'yes' or 'no'.")

    while True:
        pucca_house = input(
            "Does the family currently own a pucca house anywhere in India? (yes/no): "
        ).strip().lower()

        if pucca_house == "no":
            break
        elif pucca_house == "yes":
            print("\nPMAY-U 2.0 — Does not appear applicable.")
            return False
        else:
            print("\nPlease enter only 'yes' or 'no'.")

    while True:
        previous_housing = input(
            "Has the family received a government housing benefit during the last 20 years? (yes/no): "
        ).strip().lower()

        if previous_housing == "no":
            break
        elif previous_housing == "yes":
            print("\nPMAY-U 2.0 — Does not appear applicable.")
            return False
        else:
            print("\nPlease enter only 'yes' or 'no'.")

    if annual_income <= 300000:
        category = "EWS"
    elif annual_income <= 600000:
        category = "LIG"
    else:
        category = "MIG"

    print("\nPMAY-U 2.0 — Potentially relevant for further verification.")
    print(f"Reported income falls within the {category} screening range.")

    return True


def check_pmjjby(age):
    if age < 18 or age > 50:
        return False

    print(f"\nPMJJBY — Age {age}: Potentially relevant for new enrolment.")

    while True:
        account = input(
            "Does this person have a bank/Post Office account with a participating institution? (yes/no): "
        ).strip().lower()

        if account == "yes":
            break
        elif account == "no":
            print("PMJJBY — Account condition not met based on the information provided.")
            return False
        else:
            print("Please enter only 'yes' or 'no'.")

    while True:
        enrolled = input("Is this person already enrolled in PMJJBY? (yes/no): ").strip().lower()

        if enrolled == "yes":
            print("PMJJBY — Already enrolled.")
            return False
        elif enrolled == "no":
            break
        else:
            print("Please enter only 'yes' or 'no'.")

    print("PMJJBY — Potentially relevant for new enrolment.")
    return True


def check_pmsby(age):
    if age < 18 or age > 70:
        return False

    print(f"\nPMSBY — Age {age}: Potentially relevant for new enrolment.")

    while True:
        account = input(
            "Does this person have a bank/Post Office account with a participating institution? (yes/no): "
        ).strip().lower()

        if account == "yes":
            break
        elif account == "no":
            print("PMSBY — Account condition not met based on the information provided.")
            return False
        else:
            print("Please enter only 'yes' or 'no'.")

    while True:
        enrolled = input("Is this person already enrolled in PMSBY? (yes/no): ").strip().lower()

        if enrolled == "yes":
            print("PMSBY — Already enrolled.")
            return False
        elif enrolled == "no":
            break
        else:
            print("Please enter only 'yes' or 'no'.")

    print("PMSBY — Potentially relevant for new enrolment.")
    return True


# ==============================
# MODULE 5 — MASTER FUNCTION
# ==============================

def run_government_scheme_screening(income):

    print("\n\n========================================")
    print(" GOVERNMENT SCHEME OPPORTUNITY CHECK")
    print("========================================")

    results = {}

    # Collect household ages ONCE
    while True:
        try:
            number = int(input("\nHow many household members do you want to screen? "))

            if number > 0:
                break
            else:
                print("Please enter at least 1 household member.")

        except ValueError:
            print("Please enter a whole number.")

    members = []

    for i in range(number):

        print(f"\n--- Household Member {i + 1} ---")

        name = input("Enter a name or label (e.g. Mother, Father, Grandma): ").strip()

        while True:
            try:
                age = int(input(f"Enter {name}'s age: "))

                if age >= 0:
                    break
                else:
                    print("Age cannot be negative.")

            except ValueError:
                print("Please enter age as a number.")

        members.append({
            "name": name,
            "age": age
        })

    # --------------------------------
    # SCHEME 1 — PM-JAY 70+
    # --------------------------------

    age_70_plus = any(member["age"] >= 70 for member in members)

    results["PM-JAY 70+"] = check_pmjay_senior(age_70_plus)

    # --------------------------------
    # SCHEME 2 — PM SURYA GHAR
    # --------------------------------

    results["PM Surya Ghar"] = check_surya_ghar()

    # --------------------------------
    # SCHEME 3 — PMAY-U 2.0
    # --------------------------------

    results["PMAY-U 2.0"] = check_pmay_u20(income)

    # --------------------------------
    # SCHEME 4 — PMJJBY
    # --------------------------------

    pmjjby_members = [
        member["name"]
        for member in members
        if 18 <= member["age"] <= 50
    ]

    if pmjjby_members:
        print("\n=== PMJJBY — NEW ENROLMENT SCREENING ===")
        print("Potentially relevant age-group members:")

        for name in pmjjby_members:
            print(f" - {name}")

        results["PMJJBY"] = True
    else:
        print("\nPMJJBY — No household member falls within the 18–50 entry-age range.")
        results["PMJJBY"] = False

    # --------------------------------
    # SCHEME 5 — PMSBY
    # --------------------------------

    pmsby_members = [
        member["name"]
        for member in members
        if 18 <= member["age"] <= 70
    ]

    if pmsby_members:
        print("\n=== PMSBY — NEW ENROLMENT SCREENING ===")
        print("Potentially relevant age-group members:")

        for name in pmsby_members:
            print(f" - {name}")

        results["PMSBY"] = True
    else:
        print("\nPMSBY — No household member falls within the 18–70 entry-age range.")
        results["PMSBY"] = False

    # --------------------------------
    # FINAL SUMMARY
    # --------------------------------

    print("\n\n========================================")
    print(" GOVERNMENT SCHEME SCREENING SUMMARY")
    print("========================================")

    for scheme, result in results.items():

        if result:
            print(f"✓ {scheme}: Potentially relevant")
        else:
            print(f"— {scheme}: Does not appear applicable")

    print("\nImportant:")
    print("This is a preliminary screening tool.")
    print("Final eligibility must be verified through the official")
    print("government scheme and application process.")

    return results

# ==============================
# MODULE 6 — FINANCIAL HEALTH SCORE
# ==============================

def financial_health_score(income, result):

    surplus = result['surplus']
    expense_pct = result['expense_pct']
    discretionary_pct = result['discretionary_pct']
    potential_saving = result['potential_monthly_saving']

    # ------------------------------
    # 1. SURPLUS / DEFICIT — 25 POINTS
    # ------------------------------

    if surplus <= 0:
        surplus_score = 0
    else:
        surplus_pct = (surplus / income) * 100

        if surplus_pct >= 30:
            surplus_score = 25
        elif surplus_pct >= 20:
            surplus_score = 20
        elif surplus_pct >= 10:
            surplus_score = 15
        elif surplus_pct >= 5:
            surplus_score = 10
        else:
            surplus_score = 5

    # ------------------------------
    # 2. SAVINGS RATE — 25 POINTS
    # ------------------------------

    savings_rate = (surplus / income) * 100

    if savings_rate <= 0:
        savings_score = 0
    elif savings_rate >= 30:
        savings_score = 25
    elif savings_rate >= 20:
        savings_score = 20
    elif savings_rate >= 10:
        savings_score = 15
    elif savings_rate >= 5:
        savings_score = 10
    else:
        savings_score = 5

    # ------------------------------
    # 3. EXPENSE BURDEN — 20 POINTS
    # ------------------------------

    if expense_pct <= 60:
        expense_score = 20
    elif expense_pct <= 70:
        expense_score = 17
    elif expense_pct <= 80:
        expense_score = 14
    elif expense_pct <= 90:
        expense_score = 8
    elif expense_pct <= 100:
        expense_score = 4
    else:
        expense_score = 0

    # ------------------------------
    # 4. SPENDING STRUCTURE — 15 POINTS
    # ------------------------------

    if discretionary_pct <= 10:
        discretionary_score = 15
    elif discretionary_pct <= 15:
        discretionary_score = 12
    elif discretionary_pct <= 20:
        discretionary_score = 9
    elif discretionary_pct <= 30:
        discretionary_score = 5
    else:
        discretionary_score = 2

    # ------------------------------
    # 5. SAVINGS OPPORTUNITY — 15 POINTS
    # ------------------------------

    potential_rate = (potential_saving / income) * 100

    if potential_rate >= 10:
        opportunity_score = 15
    elif potential_rate >= 7:
        opportunity_score = 12
    elif potential_rate >= 5:
        opportunity_score = 9
    elif potential_rate >= 2:
        opportunity_score = 5
    else:
        opportunity_score = 2

    # ------------------------------
    # FINAL SCORE
    # ------------------------------

    total_score = (
        surplus_score
        + savings_score
        + expense_score
        + discretionary_score
        + opportunity_score
    )

    # ------------------------------
    # SCORE CATEGORY
    # ------------------------------

    if total_score >= 80:
        category = "Strong"
    elif total_score >= 60:
        category = "Stable"
    elif total_score >= 40:
        category = "Needs improvement"
    else:
        category = "Needs attention"

    # ------------------------------
    # OUTPUT
    # ------------------------------

    print("\n========================================")
    print(" FINANCIAL HEALTH SCORE")
    print("========================================")

    print(f"\nOverall Score: {total_score}/100")
    print(f"Financial Position: {category}")

    print("\nScore Breakdown:")
    print(f"  Surplus / Deficit: {surplus_score}/25")
    print(f"  Savings Rate: {savings_score}/25")
    print(f"  Expense Burden: {expense_score}/20")
    print(f"  Spending Structure: {discretionary_score}/15")
    print(f"  Savings Opportunity: {opportunity_score}/15")

    print("\nNote:")
    print("This score is based only on the income and")
    print("expenditure information reported to the tool.")
    print("It is an indicative financial-health measure,")
    print("not a professional financial assessment.")

    return {
        'score': total_score,
        'category': category,
        'surplus_score': surplus_score,
        'savings_score': savings_score,
        'expense_score': expense_score,
        'discretionary_score': discretionary_score,
        'opportunity_score': opportunity_score
    }
# ==============================
# MODULE 7 — VISUAL DASHBOARD
# ==============================

def dashboard(income, expenses, result, scenarios, score_result):

    fig, axes = plt.subplots(1, 3, figsize=(16, 5))

    fig.suptitle(
        'Family Financial Health Dashboard',
        fontsize=16,
        fontweight='bold'
    )

    # ------------------------------
    # CHART 1 — EXPENSE BREAKDOWN
    # ------------------------------

    labels = []
    values = []

    for category, amount in expenses.items():
        if amount > 0:
            labels.append(category)
            values.append(amount)

    axes[0].pie(
        values,
        labels=labels,
        autopct='%1.0f%%',
        startangle=90
    )

    axes[0].set_title('Expense Breakdown')

    # ------------------------------
    # CHART 2 — INCOME VS EXPENSES
    # ------------------------------

    total_expenses = result['total_exp']
    surplus = result['surplus']

    categories = ['Income', 'Expenses', 'Surplus']
    amounts = [income, total_expenses, max(surplus, 0)]

    axes[1].bar(categories, amounts)

    axes[1].set_title('Monthly Financial Position')
    axes[1].set_ylabel('Amount (₹)')

    # ------------------------------
    # CHART 3 — 5-YEAR COMPOUNDING
    # ------------------------------

    r = 0.07 / 12
    months = list(range(61))

    for label, monthly in scenarios:
      curve = [
        monthly * ((1 + r) ** m - 1) / r
        for m in months
    ]

    axes[2].plot(
        months,
        curve,
        label=label,
        marker='o',
        markevery=12
    )

    final_value = curve[-1]

    axes[2].annotate(
        f'₹{final_value:,.0f}',
        xy=(60, final_value),
        xytext=(-5, 8),
        textcoords='offset points',
        fontsize=8
    )

    axes[2].set_xlabel('Months')
    axes[2].set_ylabel('Projected Value (₹)')
    axes[2].set_title('5-Year Compounding')
    axes[2].legend(fontsize=8)


    # ------------------------------
    # FINANCIAL HEALTH SCORE
    # ------------------------------

    score = score_result['score']
    category = score_result['category']

    fig.text(
        0.5,
        0.01,
        f'Financial Health Score: {score}/100 — {category}',
        ha='center',
        fontsize=13,
        fontweight='bold'
    )

    plt.tight_layout(rect=[0, 0.05, 1, 0.95])

    plt.savefig(
        'family_ledger_dashboard.png',
        dpi=150,
        bbox_inches='tight'
    )

    plt.show()

    print('\nDashboard saved as family_ledger_dashboard.png')

# ==============================
# FINAL RUNNER — FAMILY LEDGER
# ==============================

def run():

    print("\n========================================")
    print("          FAMILY LEDGER")
    print("     Household Financial Analysis")
    print("========================================")

    # MODULE 1 — Collect financial data
    income, expenses, current_savings = collect_data()

    # MODULE 2 — Analyse the budget
    result = analyse(income, expenses)

    # MODULE 3 — Savings opportunity
    print("\n=== SAVINGS OPPORTUNITY ===")
    potential = result['potential_monthly_saving']

    print(f"Potential monthly saving: ₹{potential:,.0f}")
    print(f"Potential annual saving: ₹{potential * 12:,.0f}")

    # MODULE 4 — Compounding projection
    scenarios = project_savings(
    current_savings,
    result
    )

    # MODULE 5 — Government scheme screening
    scheme_results = run_government_scheme_screening(income)

    # MODULE 6 — Financial Health Score
    score_result = financial_health_score(
        income,
        result
    )

    # MODULE 7 — Visual Dashboard
    dashboard(
        income,
        expenses,
        result,
        scenarios,
        score_result
    )

    print("\n========================================")
    print("       FAMILY LEDGER COMPLETE")
    print("========================================")
    print("All 7 modules have been completed.")
    print("Your financial dashboard has been generated.")


# ==============================
# START PROGRAM
# ==============================

if __name__ == "__main__":
    run()